### ISSUE TITLE
Sound after death

### ISSUE THREAD

**Issue by ashen-dawn** [Lilith-In-Starlight/Moloch-New#25]
**Describe the bug**
After dying, clicking on the death screen appears to make the sound of firing the wand.  It was not captured in this recording, but I was also able to hear enemies firing their wands. 

**To Reproduce**
1. Die with a wand
2. Left-click on the death screen

**Expected behavior**
The game should not continue running behind the death screen

**Screen capture**
https://github.com/Lilith-In-Starlight/Moloch-New/assets/989883/1a92e887-1ec9-4269-925c-0489513c63ab

**Additional context**
- Tested on [0.16.0-dev2](https://github.com/Lilith-In-Starlight/Moloch-New/releases/tag/0.16.0-dev2)
- Screen capture includes microphone audio so the mouse click can be heard

**Comment by Lilith-In-Starlight** [comment]
Will be fixed in 0.16.0dev5
