### ISSUE TITLE
Cursor outside window bounds

### ISSUE THREAD

**Issue by ashen-dawn** [Lilith-In-Starlight/Moloch-New#26]
**Describe the bug**
Moving the mouse cursor outside the window bounds can allow the player to see beyond what was intended

**To Reproduce**
1. Play the game in a window that is significantly smaller than the available desktop space
2. Move the mouse cursor to the far part of the desktop
3. Observe that the camera moves significantly farther than it does when only moving to the edge of the window

**Expected behavior**
I assume you would want to cap the distance that can be observed by clamping the mouse's position to the window bounds before moving the camera

**Screen capture**
https://github.com/Lilith-In-Starlight/Moloch-New/assets/989883/88b17b3c-21e0-483a-8d84-e863a8244c8f

**Comment by Lilith-In-Starlight** [comment]
Will be fixed in the next release (0.16.0dev3)
